default_language_version:
    python: python3.11
repos:
-   repo: local
    hooks:
      - id: black
        name: black
        entry: python3 -m black --config pyproject.toml
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: python3 -m isort
        language: system
        types: [python]

#      - id: mypy
#        name: mypy
#        exclude: ^tests/|^alembic/
#        entry: python3 -m mypy
#        language: system
#        types: [python]
#        require_serial: true
