[tool.poetry]
name = "telegram-user-bot"
version = "0.1"
description = "Telegram user bot integration for Suvvy AI"
authors = ["sushka <barabum@duck.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
