name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
#  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/telegram_suvvy_user_bot:latest -t ghcr.io/${{ github.repository_owner }}/telegram_suvvy_user_bot:${{ github.sha }} .

      - name: Push Docker Image (Latest Tag)
        run: docker push ghcr.io/${{ github.repository_owner }}/telegram_suvvy_user_bot:latest

      - name: Push Docker Image (SHA Tag)
        run: docker push ghcr.io/${{ github.repository_owner }}/telegram_suvvy_user_bot:${{ github.sha }}
