name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.set-image-name.outputs.image_name }}
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set Image Name
        id: set-image-name
        run: echo "::set-output name=image_name::ghcr.io/${{ github.repository_owner }}/telegram_suvvy_user_bot:${{ github.sha }}"

      - name: Build Docker Image
        run: docker build -t ${{ steps.set-image-name.outputs.image_name }} .

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Image to GHCR
        run: docker push ${{ needs.build.outputs.image_name }}