name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set Image Name
        id: set-image-name
        run: echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/telegram_suvvy_user_bot:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Save Docker Image
        run: docker save $IMAGE_NAME > image.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: image.tar

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download Image Artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: .

      - name: Load Docker Image
        run: docker load < image.tar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Image to GHCR
        run: docker push $IMAGE_NAME
